// src/components/ArticleHeadline.tsx
import React, { FC } from 'react'
import { GatsbyImage, IGatsbyImageData } from 'gatsby-plugin-image'
import { LocalizedLink, useLocalization } from 'gatsby-theme-i18n'

const ArticleHeadline: FC<{
  title: string
  description: string
  img: IGatsbyImageData
  to: string
  alt: string
  lastUpdated?: number
  readingTime?: number
}> = ({ title, description, img, to, alt, lastUpdated, readingTime }) => {
  const { locale } = useLocalization()
  return (
    <LocalizedLink
      to={to}
      language={locale}
      className="
      rounded-md
      hover:(shadow-lg scale-103)
      md:hover:scale-105
      light:hover:bg-gray-50
      dark:hover:bg-gray-800
      transition
      duration-500
      flex
      mb-4
      transform
    "
    >
      <GatsbyImage
        className="m-2 sm:m-3 rounded overflow-visible"
        alt={alt}
        image={img}
      />

      <div className="p-1 sm:p-2 flex flex-1 space-y-2 flex-col justify-between">
        <div className="sm:space-y-1">
          <h2
            className="
            line-clamp-2
            transition
            duration-200
            text-xl
            sm:text-2xl
          "
          >
            {title}
          </h2>

          <p className="light:text-gray-500 dark:text-gray-400 line-clamp-2 md:line-clamp-3">
            {description}
          </p>
        </div>

        {(lastUpdated || readingTime) && (
          <div className="time opacity-50 no-underline text-sm -mt-1">
            {lastUpdated && (
              <span className="mr-4 no-underline">
                {new Date(lastUpdated).toLocaleDateString()}
              </span>
            )}
            {readingTime && <span>{readingTime} min read</span>}
          </div>
        )}
      </div>
    </LocalizedLink>
  )
}

export default ArticleHeadline

// components/ArticleHeadline.vue
<template>
  <a
    class="
      rounded-md
      overflow-hidden
      shadow
      hover:shadow-lg
      hover:bg-gray-50
      transition
      duration-200
      flex
      mb-4
    "
    :href="to"
  >
    <img
      :width="500"
      :height="500"
      loading="lazy"
      class="w-16 h-16 m-2 sm:m-3 rounded sm:w-32 sm:h-32"
      :alt="alt"
      :src="img"
    />

    <div class="p-1 sm:p-2 flex space-y-2 flex-col justify-between">
      <div class="sm:space-y-1">
        <h2
          class="
            hover:text-green-500
            text-gray-700
            line-clamp-2
            transition
            duration-200
            text-xl
            sm:text-2xl
          "
        >
          {{ title }}
        </h2>

        <p class="text-gray-500 line-clamp-2 md:line-clamp-3">
          {{ description }}
        </p>
      </div>

      <div
        v-if="or(lastUpdated, readingTime)"
        class="time opacity-50 no-underline text-sm -mt-1"
      >
        <span v-if="lastUpdated" class="mr-4 no-underline"
          >{{ new Date(lastUpdated).toLocaleDateString(lang) }}
        </span>
        <span v-if="readingTime">{{ readingTime }} min read</span>
      </div>
    </div>
  </a>
</template>

<script setup lang="ts">
import { defineProps } from 'vue'
import { or } from 'fonction'
import { useLang } from '../_utils/language'

const { lang } = useLang()
defineProps<{
  title: string
  description: string
  img: string
  to: string
  alt: string
  lastUpdated?: number
  readingTime?: number
}>()
</script>
