// frontend/src/components/Posts.vue
<template>
  <div class="pb-84 pt-8 px-2 sm:pt-16">
    <div class="mb-5 mx-auto" style="max-width: 65ch">
      <h1 class="text-2xl mb-4">Blog</h1>

      <article-headline
        v-for="{ path, meta } in posts"
        :key="path"
        :title="meta.frontmatter.title"
        :description="meta.frontmatter.description"
        :img="meta.frontmatter.thumbnail"
        alt="thumbnail"
        :reading-time="meta.frontmatter.readingTime.text"
        :to="path"
        :updated-at="
          formatDate(meta.frontmatter.updatedAt).toLocaleDateString()
        "
      />
    </div>
  </div>
</template>

<script setup lang="ts">
import { useHead } from '@vueuse/head'
import { computed } from 'vue'
import { useI18n } from 'vue-i18n'
import type { RouteRecordNormalized } from 'vue-router'
import { useRoute, useRouter } from 'vue-router'

import ArticleHeadline from '@/components/ArticleHeadline.vue'
import { isStartWithSlashJaSlash } from '@/functions/utils'
const { locale, t } = useI18n()
const { path } = useRoute()
const { getRoutes } = useRouter()
const formatDate = (val: string): Date => new Date(Date.parse(val))

const lang = isStartWithSlashJaSlash(path) ? 'ja' : 'en'
const prefix = lang === 'ja' ? '/ja/posts/' : '/posts/'
const filterPosts = ({ meta, path }: RouteRecordNormalized) =>
  path.startsWith(prefix) && meta.frontmatter
const posts = computed(() => getRoutes().filter(filterPosts))

const jaPath = 'https://miyauchi.dev/ja/posts'
const enPath = 'https://miyauchi.dev/posts'
const title = `${t('blog')} | Tomoki Miyauchi`
const href = locale.value === 'ja' ? jaPath : enPath
useHead({
  title,
  meta: [
    { name: 'description', content: t('description') },
    { property: 'og:title', content: title },
    { property: 'og:description', content: "Tomoki Miyauchi's Blog" },
    { property: 'og:image', content: 'https://miyauchi.dev/logo.png' },
    { property: 'og:site_name', content: 'TM Blog' }
  ],
  link: [
    {
      ref: 'canonical',
      href
    },
    {
      ref: 'alternate',
      hreflang: 'en',
      href: enPath
    },
    {
      ref: 'alternate',
      hreflang: 'ja',
      href: jaPath
    },
    {
      ref: 'alternate',
      hreflang: 'x-default',
      href: enPath
    }
  ]
})
</script>

<i18n lang="yml">
en:
  blog: Blog
  description: Tomoki Miyauchi's technical blog. Mainly aim to disseminate technical and useful information such as information on the latest technology related to the Web and introduction of what was created as a project. I will send live information with a lot of actual code.

ja:
  blog: ブログ
  description: Tomoki Miyauchiの技術ブログです。主にWebに関する最新技術の情報や、プロジェクトとして作ったものの紹介など、技術的で役立つ情報の発信を目指します。実際のコードを多めに、生きた情報の発信をします。
</i18n>

// src/pages/posts.tsx
import React, { FC } from 'react'
import { PageProps, graphql } from 'gatsby'
import { BlogPostsQuery } from '../../graphql-types'
import ArticleHeadline from '../components/ArticleHeadline'
import Layout from '../components/Layout'
import Seo from '../components/seo'
import { Helmet } from 'react-helmet'

const Posts: FC<PageProps<BlogPostsQuery>> = (a) => {
  const {
    data,
    pageContext: { originalPath, locale },
    location
  } = a
  const {
    allMdx,
    site: { siteMetadata }
  } = data
  const { siteUrl } = siteMetadata

  const p = locale === 'en' ? '/' : '/ja'

  const fullpath = new URL(location.pathname, siteUrl).toString()

  const breadcrumbList = {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: [
      {
        '@type': 'ListItem',
        position: 1,
        name: 'Home',
        item: new URL(p, siteUrl)
      },
      {
        '@type': 'ListItem',
        position: 2,
        name: 'Blog',
        item: fullpath
      }
    ]
  }

  return (
    <Layout originalPath={originalPath} currentPath={location.pathname}>
      <Seo
        title="Blog"
        description="Tomoki Miyauchi's technical blog. Mainly aim to disseminate technical and useful information such as information on the latest technology related to the Web and introduction of what was created as a project. I will send live information with a lot of actual code."
        fullpath={fullpath}
      />

      <Helmet>
        <script type="application/ld+json">
          {JSON.stringify(breadcrumbList)}
        </script>

        <meta name="og:type" content="website" />
        <meta name="twitter:card" content="summary" />
      </Helmet>

      <div className="container mx-auto">
        <h1 className="text-center text-5xl my-4 md:my-10">Blog</h1>
        <ul className="mx-auto md:grid md:grid-cols-2 md:gap-14 max-w-5xl">
          {allMdx.nodes.map(
            ({
              frontmatter: { title, thumbnail, description, date, slug, tags },
              fields
            }) => (
              <li className="-mx-2 md:mx-auto" key={slug}>
                <ArticleHeadline
                  title={title}
                  description={description}
                  to={slug}
                  img={thumbnail.childImageSharp.gatsbyImageData}
                  readingTime={fields.readingTime.text}
                  lastUpdated={date}
                  tags={tags ?? []}
                  alt="thumbnail"
                />
              </li>
            )
          )}
        </ul>
      </div>
    </Layout>
  )
}

export default Posts

export const query = graphql`
  query BlogPosts($locale: String!) {
    allMdx(
      filter: { fields: { locale: { eq: $locale } } }
      sort: { fields: frontmatter___date, order: DESC }
    ) {
      nodes {
        frontmatter {
          title
          description
          date
          thumbnail {
            childImageSharp {
              gatsbyImageData(layout: FIXED, aspectRatio: 1, width: 80)
            }
          }
          slug
          tags
        }
        fields {
          readingTime {
            text
          }
        }
      }
    }
    site {
      siteMetadata {
        siteUrl
      }
    }
  }
`
